// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

contract AgentRegistry is ERC721, Ownable {
    using ECDSA for bytes32;

    // Mapping from agent address to their metadata URI
    mapping(address => string) private _agentURIs;
    
    // Mapping from agent address to owner address
    mapping(address => address) private _agentOwners;

    // Track list of all registered agents for easy on-chain query
    address[] private _registeredAgentsList;
    mapping(address => uint256) private _agentListIndex;

    event AgentRegistered(address indexed agentAddress, address indexed owner, string agentURI);
    event AgentDeregistered(address indexed agentAddress);

    constructor() ERC721("GigMarket AI Agent Identity", "GMAI") Ownable(msg.sender) {}

    /**
     * @notice Registers a new AI Agent on-chain.
     * @param agentAddress The public key address of the AI agent.
     * @param agentURI The metadata URI containing agent description, capabilities, endpoints, model, etc.
     * @param signature Cryptographic signature generated by the agent's private key signing the hash of (owner, agentURI, nonce).
     */
    function registerAgent(
        address agentAddress,
        string calldata agentURI,
        bytes calldata signature
    ) external {
        require(agentAddress != address(0), "Invalid agent address");
        require(bytes(agentURI).length > 0, "Empty agent URI");
        require(_agentOwners[agentAddress] == address(0), "Agent already registered");

        // Verify cryptographic signature to prove agent controls their own key and authorizes this owner
        bytes32 messageHash = keccak256(abi.encodePacked(msg.sender, agentURI, agentAddress));
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);
        
        address recoveredSigner = ethSignedMessageHash.recover(signature);
        require(recoveredSigner == agentAddress, "Invalid agent signature");

        // Mint ERC721 token representing the Agent Identity to the owner (msg.sender)
        uint256 tokenId = uint256(uint160(agentAddress));
        _safeMint(msg.sender, tokenId);

        _agentURIs[agentAddress] = agentURI;
        _agentOwners[agentAddress] = msg.sender;

        _agentListIndex[agentAddress] = _registeredAgentsList.length;
        _registeredAgentsList.push(agentAddress);

        emit AgentRegistered(agentAddress, msg.sender, agentURI);
    }

    /**
     * @notice Deregisters an AI agent. Can only be called by the agent's owner.
     */
    function deregisterAgent(address agentAddress) external {
        require(_agentOwners[agentAddress] == msg.sender, "Not the owner of the agent");

        uint256 tokenId = uint256(uint160(agentAddress));
        _burn(tokenId);

        delete _agentURIs[agentAddress];
        delete _agentOwners[agentAddress];

        // Remove from list
        uint256 index = _agentListIndex[agentAddress];
        uint256 lastIndex = _registeredAgentsList.length - 1;
        if (index != lastIndex) {
            address lastAgent = _registeredAgentsList[lastIndex];
            _registeredAgentsList[index] = lastAgent;
            _agentListIndex[lastAgent] = index;
        }
        _registeredAgentsList.pop();

        emit AgentDeregistered(agentAddress);
    }

    /**
     * @notice Checks if an address is a registered AI Agent.
     */
    function isRegisteredAgent(address agentAddress) external view returns (bool) {
        return _agentOwners[agentAddress] != address(0);
    }

    /**
     * @notice Returns the metadata URI of the registered agent.
     */
    function getAgentURI(address agentAddress) external view returns (string memory) {
        require(_agentOwners[agentAddress] != address(0), "Agent not registered");
        return _agentURIs[agentAddress];
    }

    /**
     * @notice Returns the owner of the registered agent.
     */
    function getAgentOwner(address agentAddress) external view returns (address) {
        return _agentOwners[agentAddress];
    }

    /**
     * @notice Returns the complete list of registered agents.
     */
    function getRegisteredAgents() external view returns (address[] memory) {
        return _registeredAgentsList;
    }
}
